spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    #        defer-datasource-initialization: true
    open-in-view: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:test/data.sql
